#############################################################################
# Makefile for building: bin/Graphics-Project-1.app/Contents/MacOS/Graphics-Project-1
# Generated by qmake (2.01a) (Qt 4.7.0) on: Thu Feb 4 23:01:17 2010
# Project:  Graphics-Project-1.pro
# Template: app
# Command: /usr/local/Trolltech/Qt-4.7.0/bin/qmake -macx -o Makefile Graphics-Project-1.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.7.0/mkspecs/macx-g++ -I. -I/usr/local/Trolltech/Qt-4.7.0/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Trolltech/Qt-4.7.0/include/QtCore -I/usr/local/Trolltech/Qt-4.7.0/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Trolltech/Qt-4.7.0/include/QtGui -I/usr/local/Trolltech/Qt-4.7.0/lib/QtOpenGL.framework/Versions/4/Headers -I/usr/local/Trolltech/Qt-4.7.0/include/QtOpenGL -I/usr/local/Trolltech/Qt-4.7.0/include -I. -Isrc/main -Isrc/re330 -I/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/System/Library/Frameworks/AGL.framework/Headers -Ibuild -F/usr/local/Trolltech/Qt-4.7.0/lib
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/usr/local/Trolltech/Qt-4.7.0/lib -L/usr/local/Trolltech/Qt-4.7.0/lib -lGLEW -framework OpenGL -framework AGL -framework QtOpenGL -L/usr/local/Trolltech/Qt-4.7.0/lib -F/usr/local/Trolltech/Qt-4.7.0/lib -framework QtGui -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/local/Trolltech/Qt-4.7.0/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = src/main/main.cpp \
		src/main/MainWidget.cpp \
		src/main/MainWindow.cpp \
		src/main/RenderWidget0.cpp \
		src/re330/BasicMath.cpp \
		src/re330/GLRenderContext.cpp \
		src/re330/GLWidget.cpp \
		src/re330/Matrix4.cpp \
		src/re330/RenderContext.cpp \
		src/re330/SceneManager.cpp \
		src/re330/VertexData.cpp \
		src/re330/VertexDeclaration.cpp build/moc_MainWindow.cpp \
		build/moc_GLWidget.cpp
OBJECTS       = build/main.o \
		build/MainWidget.o \
		build/MainWindow.o \
		build/RenderWidget0.o \
		build/BasicMath.o \
		build/GLRenderContext.o \
		build/GLWidget.o \
		build/Matrix4.o \
		build/RenderContext.o \
		build/SceneManager.o \
		build/VertexData.o \
		build/VertexDeclaration.o \
		build/moc_MainWindow.o \
		build/moc_GLWidget.o
DIST          = /usr/local/Trolltech/Qt-4.7.0/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/common/mac.conf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/common/mac-g++.conf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/mac/default_pre.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/mac/default_post.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/mac/x86_64.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/mac/objective_c.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/unix/opengl.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/mac/rez.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/mac/sdk.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/lex.prf \
		Graphics-Project-1.pro
QMAKE_TARGET  = Graphics-Project-1
DESTDIR       = bin/
TARGET        = bin/Graphics-Project-1.app/Contents/MacOS/Graphics-Project-1

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile bin/Graphics-Project-1.app/Contents/PkgInfo bin/Graphics-Project-1.app/Contents/Resources/empty.lproj bin/Graphics-Project-1.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/Graphics-Project-1.app/Contents/MacOS/ || $(MKDIR) bin/Graphics-Project-1.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Graphics-Project-1.pro  /usr/local/Trolltech/Qt-4.7.0/mkspecs/macx-g++/qmake.conf /usr/local/Trolltech/Qt-4.7.0/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/common/mac.conf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/common/mac-g++.conf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/mac/default_pre.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/mac/default_post.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/mac/x86_64.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/mac/objective_c.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/unix/opengl.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/mac/rez.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/mac/sdk.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.7.0/lib/QtOpenGL.framework/QtOpenGL.prl \
		/usr/local/Trolltech/Qt-4.7.0/lib/QtGui.framework/QtGui.prl \
		/usr/local/Trolltech/Qt-4.7.0/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -macx -o Makefile Graphics-Project-1.pro
/usr/local/Trolltech/Qt-4.7.0/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/common/mac.conf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/common/mac-g++.conf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/mac/default_pre.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/mac/dwarf2.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/debug.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/mac/default_post.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/mac/x86_64.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/mac/objective_c.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/unix/opengl.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/mac/rez.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/mac/sdk.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.7.0/lib/QtOpenGL.framework/QtOpenGL.prl:
/usr/local/Trolltech/Qt-4.7.0/lib/QtGui.framework/QtGui.prl:
/usr/local/Trolltech/Qt-4.7.0/lib/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -macx -o Makefile Graphics-Project-1.pro

bin/Graphics-Project-1.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) bin/Graphics-Project-1.app/Contents || $(MKDIR) bin/Graphics-Project-1.app/Contents 
	@$(DEL_FILE) bin/Graphics-Project-1.app/Contents/PkgInfo
	@echo "APPL????" >bin/Graphics-Project-1.app/Contents/PkgInfo
bin/Graphics-Project-1.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) bin/Graphics-Project-1.app/Contents/Resources || $(MKDIR) bin/Graphics-Project-1.app/Contents/Resources 
	@touch bin/Graphics-Project-1.app/Contents/Resources/empty.lproj
	
bin/Graphics-Project-1.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) bin/Graphics-Project-1.app/Contents || $(MKDIR) bin/Graphics-Project-1.app/Contents 
	@$(DEL_FILE) bin/Graphics-Project-1.app/Contents/Info.plist
	@sed -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,Graphics-Project-1,g" -e "s,@TYPEINFO@,????,g" /usr/local/Trolltech/Qt-4.7.0/mkspecs/macx-g++/Info.plist.app >bin/Graphics-Project-1.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) build/Graphics-Project-11.0.0 || $(MKDIR) build/Graphics-Project-11.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/Graphics-Project-11.0.0/ && $(COPY_FILE) --parents src/main/MainWidget.h src/main/MainWindow.h src/main/RenderWidget0.h src/re330/BasicMath.h src/re330/Camera.h src/re330/Frustum.h src/re330/glew.h src/re330/GLRenderContext.h src/re330/GLRenderWidget.h src/re330/GLWidget.h src/re330/Matrix4.h src/re330/Node.h src/re330/Object.h src/re330/RE330_global.h src/re330/RenderContext.h src/re330/RenderWidget.h src/re330/SceneManager.h src/re330/Singleton.h src/re330/Vector3.h src/re330/Vector4.h src/re330/VertexData.h src/re330/VertexDeclaration.h src/re330/wglew.h build/Graphics-Project-11.0.0/ && $(COPY_FILE) --parents src/main/main.cpp src/main/MainWidget.cpp src/main/MainWindow.cpp src/main/RenderWidget0.cpp src/re330/BasicMath.cpp src/re330/GLRenderContext.cpp src/re330/GLWidget.cpp src/re330/Matrix4.cpp src/re330/RenderContext.cpp src/re330/SceneManager.cpp src/re330/VertexData.cpp src/re330/VertexDeclaration.cpp build/Graphics-Project-11.0.0/ && (cd `dirname build/Graphics-Project-11.0.0` && $(TAR) Graphics-Project-11.0.0.tar Graphics-Project-11.0.0 && $(COMPRESS) Graphics-Project-11.0.0.tar) && $(MOVE) `dirname build/Graphics-Project-11.0.0`/Graphics-Project-11.0.0.tar.gz . && $(DEL_FILE) -r build/Graphics-Project-11.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r bin/Graphics-Project-1.app
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: build/moc_MainWindow.cpp build/moc_GLWidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc_MainWindow.cpp build/moc_GLWidget.cpp
build/moc_MainWindow.cpp: src/main/RenderWidget0.h \
		src/re330/GLRenderWidget.h \
		src/re330/RE330_global.h \
		src/re330/RenderWidget.h \
		src/re330/GLWidget.h \
		src/re330/GLRenderContext.h \
		src/re330/glew.h \
		src/re330/RenderContext.h \
		src/re330/Singleton.h \
		src/re330/Camera.h \
		src/re330/Frustum.h \
		src/re330/Matrix4.h \
		src/re330/Vector4.h \
		src/re330/Vector3.h \
		src/re330/Object.h \
		src/re330/VertexData.h \
		src/re330/VertexDeclaration.h \
		src/re330/SceneManager.h \
		src/main/MainWindow.h
	/usr/local/Trolltech/Qt-4.7.0/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/main/MainWindow.h -o build/moc_MainWindow.cpp

build/moc_GLWidget.cpp: src/re330/RE330_global.h \
		src/re330/GLRenderContext.h \
		src/re330/glew.h \
		src/re330/RenderContext.h \
		src/re330/Singleton.h \
		src/re330/Camera.h \
		src/re330/Frustum.h \
		src/re330/Matrix4.h \
		src/re330/Vector4.h \
		src/re330/Vector3.h \
		src/re330/Object.h \
		src/re330/VertexData.h \
		src/re330/VertexDeclaration.h \
		src/re330/GLWidget.h
	/usr/local/Trolltech/Qt-4.7.0/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/re330/GLWidget.h -o build/moc_GLWidget.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

build/main.o: src/main/main.cpp src/main/MainWindow.h \
		src/main/RenderWidget0.h \
		src/re330/GLRenderWidget.h \
		src/re330/RE330_global.h \
		src/re330/RenderWidget.h \
		src/re330/GLWidget.h \
		src/re330/GLRenderContext.h \
		src/re330/glew.h \
		src/re330/RenderContext.h \
		src/re330/Singleton.h \
		src/re330/Camera.h \
		src/re330/Frustum.h \
		src/re330/Matrix4.h \
		src/re330/Vector4.h \
		src/re330/Vector3.h \
		src/re330/Object.h \
		src/re330/VertexData.h \
		src/re330/VertexDeclaration.h \
		src/re330/SceneManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o src/main/main.cpp

build/MainWidget.o: src/main/MainWidget.cpp src/main/MainWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/MainWidget.o src/main/MainWidget.cpp

build/MainWindow.o: src/main/MainWindow.cpp src/main/MainWindow.h \
		src/main/RenderWidget0.h \
		src/re330/GLRenderWidget.h \
		src/re330/RE330_global.h \
		src/re330/RenderWidget.h \
		src/re330/GLWidget.h \
		src/re330/GLRenderContext.h \
		src/re330/glew.h \
		src/re330/RenderContext.h \
		src/re330/Singleton.h \
		src/re330/Camera.h \
		src/re330/Frustum.h \
		src/re330/Matrix4.h \
		src/re330/Vector4.h \
		src/re330/Vector3.h \
		src/re330/Object.h \
		src/re330/VertexData.h \
		src/re330/VertexDeclaration.h \
		src/re330/SceneManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/MainWindow.o src/main/MainWindow.cpp

build/RenderWidget0.o: src/main/RenderWidget0.cpp src/main/RenderWidget0.h \
		src/re330/GLRenderWidget.h \
		src/re330/RE330_global.h \
		src/re330/RenderWidget.h \
		src/re330/GLWidget.h \
		src/re330/GLRenderContext.h \
		src/re330/glew.h \
		src/re330/RenderContext.h \
		src/re330/Singleton.h \
		src/re330/Camera.h \
		src/re330/Frustum.h \
		src/re330/Matrix4.h \
		src/re330/Vector4.h \
		src/re330/Vector3.h \
		src/re330/Object.h \
		src/re330/VertexData.h \
		src/re330/VertexDeclaration.h \
		src/re330/SceneManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/RenderWidget0.o src/main/RenderWidget0.cpp

build/BasicMath.o: src/re330/BasicMath.cpp src/re330/BasicMath.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/BasicMath.o src/re330/BasicMath.cpp

build/GLRenderContext.o: src/re330/GLRenderContext.cpp src/re330/GLRenderContext.h \
		src/re330/glew.h \
		src/re330/RE330_global.h \
		src/re330/RenderContext.h \
		src/re330/Singleton.h \
		src/re330/Camera.h \
		src/re330/Frustum.h \
		src/re330/Matrix4.h \
		src/re330/Vector4.h \
		src/re330/Vector3.h \
		src/re330/Object.h \
		src/re330/VertexData.h \
		src/re330/VertexDeclaration.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/GLRenderContext.o src/re330/GLRenderContext.cpp

build/GLWidget.o: src/re330/GLWidget.cpp src/re330/GLWidget.h \
		src/re330/RE330_global.h \
		src/re330/GLRenderContext.h \
		src/re330/glew.h \
		src/re330/RenderContext.h \
		src/re330/Singleton.h \
		src/re330/Camera.h \
		src/re330/Frustum.h \
		src/re330/Matrix4.h \
		src/re330/Vector4.h \
		src/re330/Vector3.h \
		src/re330/Object.h \
		src/re330/VertexData.h \
		src/re330/VertexDeclaration.h \
		src/re330/GLRenderWidget.h \
		src/re330/RenderWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/GLWidget.o src/re330/GLWidget.cpp

build/Matrix4.o: src/re330/Matrix4.cpp src/re330/Matrix4.h \
		src/re330/Vector4.h \
		src/re330/RE330_global.h \
		src/re330/Vector3.h \
		src/re330/BasicMath.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Matrix4.o src/re330/Matrix4.cpp

build/RenderContext.o: src/re330/RenderContext.cpp src/re330/RenderContext.h \
		src/re330/RE330_global.h \
		src/re330/Singleton.h \
		src/re330/Camera.h \
		src/re330/Frustum.h \
		src/re330/Matrix4.h \
		src/re330/Vector4.h \
		src/re330/Vector3.h \
		src/re330/Object.h \
		src/re330/VertexData.h \
		src/re330/VertexDeclaration.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/RenderContext.o src/re330/RenderContext.cpp

build/SceneManager.o: src/re330/SceneManager.cpp src/re330/SceneManager.h \
		src/re330/RE330_global.h \
		src/re330/Camera.h \
		src/re330/Frustum.h \
		src/re330/Matrix4.h \
		src/re330/Vector4.h \
		src/re330/Vector3.h \
		src/re330/Object.h \
		src/re330/VertexData.h \
		src/re330/VertexDeclaration.h \
		src/re330/RenderContext.h \
		src/re330/Singleton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/SceneManager.o src/re330/SceneManager.cpp

build/VertexData.o: src/re330/VertexData.cpp src/re330/VertexData.h \
		src/re330/RE330_global.h \
		src/re330/VertexDeclaration.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/VertexData.o src/re330/VertexData.cpp

build/VertexDeclaration.o: src/re330/VertexDeclaration.cpp src/re330/VertexDeclaration.h \
		src/re330/RE330_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/VertexDeclaration.o src/re330/VertexDeclaration.cpp

build/moc_MainWindow.o: build/moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_MainWindow.o build/moc_MainWindow.cpp

build/moc_GLWidget.o: build/moc_GLWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_GLWidget.o build/moc_GLWidget.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

